### ISSUE TITLE
linkinator GitHub Action and CLI report very inconsistent results

### ISSUE THREAD

**Issue by DavidAnson** [JustinBeckwith/linkinator-action#42]
Here are 3 workflows running against the same repo (https://github.com/DavidAnson/markdownlint) at the same time (a moment ago):

markdown-link-check: https://github.com/DavidAnson/Workflows/runs/1674500291?check_suite_focus=true

- Reports 9+117+6+20+12="164 links checked."
- Shows 148 instances of "Status: 200" in logs

linkinator CLI: https://github.com/DavidAnson/Workflows/runs/1674500251?check_suite_focus=true

- Reports "Successfully scanned 586 links"
- Shows 174 instances of "[200]" in logs

linkinator GitHub Action: https://github.com/DavidAnson/Workflows/runs/1674500286?check_suite_focus=true

- Reports "Scanned total of 87 links!"
- Shows 87 instances of "[200]" in logs

I believe I have configured all of these tools to scan the same content. markdown-link-check is provided for comparison because it's what I originally used. linkinator doesn't need to match its behavior, but I'd expect the numbers to be very similar.

- The linkinator GitHub Action is the only tool that's consistent in its reporting, but seems to be ignoring about half the links.
- The linkinator CLI self-reports only 30% of the links it claims to have scanned. Its 174 number is in the ballpark of 148/164 from markdown-link-check, but I'm curious what it's scanning that's extra.
- And why are the linkinator CLI and GitHub Action so different here (the highest and lowest of the three tools)?

Thanks for the help!

**Comment by XhmikosR** [comment]
I actually hit this in my test branch too. I get 299 links https://github.com/twbs/bootstrap/runs/1702622907#step:9:449, while with the CLI I get 699 links https://github.com/twbs/bootstrap/runs/1701506618#step:7:42

**Comment by XhmikosR** [comment]
Another one:

* https://github.com/twbs/bootstrap/compare/main-xmr-linkinator-action
* 222 links vs 712 links on main

AFAICT the linkinator arguments should be the same, so this is weird indeed :/

**Comment by JustinBeckwith** [comment]
Ok so good news, with https://github.com/JustinBeckwith/linkinator/pull/277 which landed in [linkinator@2.13.6](https://www.npmjs.com/package/linkinator/v/2.13.6), both the GitHub Action and the CLI scan are returning 89 results:
https://github.com/JustinBeckwith/markdownlint/actions/runs/587362108

Next I'll take a look at markdown link check.  One thing that may be causing the difference - I'm super careful about not scanning the same link twice.  I think I may also strip URL fragments, but I need to poke at what this other tool is up to.

**Comment by DavidAnson** [comment]
w00t

**Comment by JustinBeckwith** [comment]
Ok I have an early, messy analysis [here](https://docs.google.com/spreadsheets/d/1Gt4jafCR9rYxH4kBFp_mqxyy7YqB8wUUb6K0nf--10I/edit#gid=1444897171).  The differences break out into a few categories:

### Re-scanning checked links
Markdown lint is reporting the same link on multiple pages where it's scanned.  Linkinator will only report a given URL once across all scanned documents.  

Linkinator _could_ specifically report this case, and include it in the final report.  Unclear if that would be good or bad or just different :)

### URI Fragments
Markdown lint is reporting self-links to a page that are using URI Fragments.  It's reporting a bunch of links like `[✓] doc/Rules.md#md003 → Status: 200`.  Linkinator specifically strips / deduplicates these, because they will not lead to a 404. 

Again - Linkinator _could_ ignore doing the scan, and just report success.  It's just different.  

### Skipped links
The setup you have for linkinator skips urls with `lib` in the path like this one:
```
[✓] https://github.com/DavidAnson/markdownlint/tree/main/lib → Status: 200
```

And it's set up to skip all links with `style` in the URL.  I suspect maybe this wasn't your intent :) 
```
[✓] https://cirosantilli.com/markdown-style-guide#line-wrapping → Status: 200
```

Also `/test` directory links.  


I think what we have in both the CLI and the Action here is accurate, just maybe not represented in the same way as markdownlint.  I'd love to hear opinions on how we should change things!

**Comment by DavidAnson** [comment]
Awesome! I think the current reporting behavior of your tool makes sense as-is. Regarding lib and style, those are excluded as a workaround for linkinator reporting directory links as failing (<https://github.com/JustinBeckwith/linkinator/issues/212>). Seems like my exclusion was too broad - I can update that if there's a way. The link looks like `[style](style)`, so my only option would seem to be adding `^` or `$`?

**Comment by JustinBeckwith** [comment]
Oh!  I added a `--directory-listing` flag that should do just this ....  I tried:
```
linkinator '**/*.md' --directory-listing --skip 'node_modules/ test/ ^https://github.com/.*/search\\?q='
```

And it seems to work pretty well.  Thinking out loud ... maybe `--directory-listing` should be the default for the GitHub Action?  I already default the `--markdown` flag.

**Comment by DavidAnson** [comment]
Nice!
