### ISSUE TITLE
`silent` isn't recognized

### ISSUE THREAD

**Issue by XhmikosR** [JustinBeckwith/linkinator-action#50]
Hey, @JustinBeckwith! I decided to give this a go and noticed that `silent` isn't recognized like on the CLI.

Are there any plans to add support for it and/or `verbosity` too?

Thanks!

**Comment by JustinBeckwith** [comment]
If we did this, I would want to use `verbosity` instead of `silent` - that's the direction `linkinator` itself is going to move going forward.  I'm completely open to the idea of bringing `verbosity` into the options - it just hasn't made it there yet because unlike most of the other options, the majority of that code was very specific to the CLI part of the module - which means most of it would have to be reproduced in some way here.  It's just work 😆

**Comment by JustinBeckwith** [comment]
Think this is covered now in `1.4.0`.
